INSERT INTO public.postgres_person (id, age, name, city) VALUES (1, 25, 'John Doe', 'New York');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (2, 30, 'Jane Smith', 'Los Angeles');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (3, 22, 'Bob Johnson', 'Chicago');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (4, 28, 'Alice Williams', 'San Francisco');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (5, 35, 'Michael Brown', 'Houston');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (6, 27, 'Emily Davis', 'Seattle');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (7, 31, 'Daniel Miller', 'Miami');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (8, 29, 'Olivia White', 'Denver');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (9, 26, 'Ethan Wilson', 'Boston');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (10, 33, 'Sophia Lee', 'Atlanta');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (11, 24, 'Logan Harris', 'Dallas');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (12, 32, 'Ava Garcia', 'Phoenix');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (13, 30, 'William Taylor', 'San Diego');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (14, 28, 'Emma Moore', 'Austin');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (15, 29, 'Liam Clark', 'Portland');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (16, 27, 'Isabella Allen', 'Las Vegas');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (17, 26, 'James Martinez', 'Detroit');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (18, 31, 'Mia Hall', 'Minneapolis');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (19, 23, 'Jackson Lewis', 'Philadelphia');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (20, 30, 'Avery Turner', 'Charlotte');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (21, 29, 'Madison Scott', 'San Antonio');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (22, 34, 'Noah King', 'Baltimore');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (27, 29, 'Ella Nelson', 'Denver');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (23, 25, 'Abigail Rodriguez', 'Nashville');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (24, 28, 'Benjamin Anderson', 'Indianapolis');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (25, 26, 'Chloe Thomas', 'Columbus');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (26, 32, 'Samuel Wright', 'Jacksonville');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (28, 27, 'David Hill', 'Louisville');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (29, 31, 'Lily Adams', 'Memphis');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (30, 26, 'Elijah Ward', 'Milwaukee');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (31, 33, 'Grace Turner', 'Oklahoma City');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (32, 28, 'Christopher Cooper', 'Albuquerque');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (33, 29, 'Zoe Hall', 'Tucson');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (34, 24, 'Joseph Mitchell', 'Fresno');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (35, 30, 'Aria Perez', 'Sacramento');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (36, 28, 'Henry Rivera', 'Long Beach');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (37, 27, 'Scarlett Coleman', 'Kansas City');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (38, 32, 'Matthew Stewart', 'Mesa');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (39, 29, 'Aubrey Reed', 'Virginia Beach');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (40, 26, 'Andrew Brooks', 'Atlanta');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (41, 33, 'Addison Perry', 'Colorado Springs');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (42, 28, 'Gabriel Simmons', 'Raleigh');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (43, 29, 'Natalie Bell', 'Omaha');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (44, 27, 'Nicholas Ward', 'Miami');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (45, 31, 'Sofia Thompson', 'Tulsa');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (46, 26, 'Elijah Foster', 'Oakland');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (47, 34, 'Amelia Murphy', 'Cleveland');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (48, 25, 'Jack Bryant', 'Minneapolis');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (49, 30, 'Avery Torres', 'Arlington');
INSERT INTO public.postgres_person (id, age, name, city) VALUES (50, 29, 'Penelope Wright', 'New Orleans');
